name: linkedin_share
description: "Flutter plugin enables seamless sharing of text, single files (images), and multiple files (images) directly to LinkedIn."
version: 0.0.1
homepage: https://
repository: https://

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:

  plugin:
    platforms:
      android:
        package: electrovese.linkedin_share
        pluginClass: LinkedinSharePlugin
      ios:
        pluginClass: LinkedinSharePlugin

